name: build

on:
  push:
    branches: 
      - main
  release:
    types:
      - published
      - edited

jobs:
  main:
    runs-on: ubuntu-latest

    services:
      dind:
        image: docker:dind
        ports: 
          - 2375/tcp
        env:
          DOCKER_DRIVER: overlay
          DOCKER_TLS_CERTDIR: ""
        options: "--privileged"

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: name/app

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up build tag
        id: build_tag
        shell: bash
        env:
          GITHUB_REF: ${{ github.ref }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          VERSION=$(echo "${GITHUB_REF}" | cut -d '/' -f 3)
          if [[ "$VERSION" == "main" ]]; then
            VERSION=latest
          fi
          OWNER=$( \
            echo "${GITHUB_REPOSITORY}" | \
            cut -d'/' -f1 | \
            tr '[:upper:]' '[:lower:]' \
          )
          REPO=$( \
            echo "${GITHUB_REPOSITORY}" | \
            cut -d'/' -f2 | \
            sed -r 's/([A-Z])([a-z0-9])/-\L\1\2/g' | \
            tr '[:upper:]' '[:lower:]' \
          )
          echo "::set-output name=repo::${OWNER}/${REPO}"
          echo "::set-output name=tag::${OWNER}/${REPO}:${VERSION}"

      - name: Docker build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          cache-from: type=registry,ref=${{ steps.build_tag.outputs.repo }}:latest
          cache-to: type=inline
          tags: |
            ${{ steps.build_tag.outputs.tag }}
            ghcr.io/${{ steps.build_tag.outputs.tag }}
          labels: |
            org.opencontainers.image.title=${{ github.event.repository.name }}
            org.opencontainers.image.url=${{ github.event.repository.html_url }}
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Singularity build
        id: singularity_build
        shell: bash
        env:
          DOCKER_IMAGE_NAME: ${{ steps.build_tag.outputs.tag }}
          DOCKER_HOST: "tcp://127.0.0.1:${{ job.services.dind.ports[2375] }}"
        run: |
          SINGULARITY_IMAGE_NAME=$(echo -n ${DOCKER_IMAGE_NAME} | tr -c '[:alnum:]' '-')
          echo DOCKER_HOST=$DOCKER_HOST
          docker run --rm \
            --privileged \
            --volume $(pwd):/output \
            quay.io/singularity/docker2singularity:latest \
            --name ${SINGULARITY_IMAGE_NAME} \
            ${DOCKER_IMAGE_NAME}
          SINGULARITY_IMAGE_FILE=$(find "$(pwd)/${SINGULARITY_IMAGE_NAME}.*" | head -n1)
          echo "::set-output name=image::${SINGULARITY_IMAGE_FILE}"

      - uses: BetaHuhn/do-spaces-action@v2
        with:
          access_key: ${{ secrets.DIGITALOCEAN_ACCESS_KEY }}
          secret_key: ${{ secrets.DIGITALOCEAN_SECRET_KEY }}
          space_name: ${{ secrets.DIGITALOCEAN_SPACE_NAME }}
          space_region: ${{ secrets.DIGITALOCEAN_REGION }}
          source: ${{ steps.singularity_build.outputs.image }}
          out_dir: singularity
